[profile.default]
solc-version = "0.8.26"
src = "contracts"
out = "out"
libs = ["node_modules", "lib"]
runs = 1
optimizer = true
optimizer-runs = 1
via-ir = true
fs_permissions = [{ access = "read-write", path = "./" }]
evm_version = "paris"
